### ISSUE TITLE
Možnost uložení grafu jako obrázek

### ISSUE THREAD

**Issue by kaklik** [povik/envdeploy#1]
Na rozdíl od "desktop verze"  nemá současná implementace možnost uložení grafu tak, aby šel přímo použít v dokumentu. 

![image](https://user-images.githubusercontent.com/1194177/61667777-36e05e80-acdb-11e9-8c6f-8e15597b3196.png)

Nejpoužitelnější způsob je vytvoření printscreenu.

**Comment by povik** [comment]
Closing as this issue is specific to one deployment of envdeploy, not the tool itself.
