### ISSUE TITLE
Ukládání notebooků

### ISSUE THREAD

**Issue by kaklik** [povik/envdeploy#2]
V případě, že notebook není vlastněn uživatelem, který ho otevře. Například ve shared_notebooks. Tak rozhraní nechá uživatele notebook "editovat" jak chce. 
Změny se ale zahodí při prvním výpadku připojení, neboť reálně nejsou nikde uloženy.

**Comment by povik** [comment]
Closing as this issue is specific to one deployment of envdeploy, not the tool itself.
