### ISSUE TITLE
Přihlašování uživatelů

### ISSUE THREAD

**Issue by kaklik** [povik/envdeploy#3]
Ukazuje se jako nepraktické, aby uživatel měl různé heslo od svého systémového účtu na serveru a od envdeploy. (Když už je potřeba, aby uživatel měl systémový účet na serveru)

@roman-dvorak navíc poznamenává, že uživatel potřebuje rootovská práva, aby byl schopen si změnit svoje uživatelské heslo k  envdeploy.

**Comment by povik** [comment]
Closing as this issue is specific to one deployment of envdeploy, not the tool itself.
